version: '3'

networks:
  monitor:
    driver: bridge

services:
  consul:
    image: openjdk:8-jre-alpine
    container_name: saas-saler-admin
    networks:
      - monitor
    volumes:
      - ./target/saas-saler-admin-0.0.1-SNAPSHOT.jar:/app/app.jar
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Xmx512m -Xms256m
    command: [ "sh", "-c", "java $${JAVA_OPTS} -Dfile.encoding=UTF-8 -Dserver.port=$${SERVER_PORT} -jar /app/app.jar --spring.profiles.active=$${SPRING_PROFILES_ACTIVE}" ]




